spring:
  application:
    name: yixue-repayment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/baby_p2p?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
    time-zone: Asia/Shanghai
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yixue.loxc.pojo.*      #所有Entity别名类所在包
server:
  port: 8088